baseURL = "/"
languageCode = "en-us"
title = "NSeed"
theme = "kube"
description = "in charge of your data"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "NSeed" # add your company name
  github = "nseedio" # add your github profile name
  twitter = "nseedio" # add your twitter profile
  email = "team@nseed.io"
  custom_css = ["css/nseed-custom.css"]
  googleAnalytics = "UA-142586684-1"
